Update pipelines to working status

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,9 +1,8 @@
 name: CI
-# TODO(jakebailey): removeme
+# TODO: readd this line and remove other trigger
+# on: pull_request
 on:
-  push:
-    branches:
-      - pnpm-workspaces-working
+  workflow_dispatch:
 
 permissions:
   contents: read
@@ -12,16 +11,12 @@ jobs:
   test:
     runs-on: ubuntu-latest
 
-    strategy:
-      fail-fast: false
-      matrix:
-        index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
-        numJobs: [20]
-
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
-          path: DefinitelyTyped
+          # Need this to be able to inquire about origin/master
+          filter: blob:none # https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
+          fetch-depth: 0 # Default is 1; need to set to 0 to get the benefits of blob:none.
       - uses: actions/setup-node@v3
         with:
           node-version: '16'
@@ -41,98 +36,45 @@ jobs:
           version: latest
           run_install: false
 
-      - name: Get pnpm cache info
-        id: pnpm-cache
-        shell: bash
-        run: |
-          echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT
-          echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT
+      # TODO(jakebailey): this won't work in PRs; we may need to once nightly
+      # refresh a new cache based on master, and then consume it here read-only in PRs.
+      # - name: Get pnpm cache info
+      #   id: pnpm-cache
+      #   shell: bash
+      #   run: |
+      #     echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT
+      #     echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT
 
-      - uses: actions/cache@v3
-        name: Setup pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.store }}
-          key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
+      # - uses: actions/cache@v3
+      #   name: Setup pnpm cache
+      #   with:
+      #     path: ${{ steps.pnpm-cache.outputs.store }}
+      #     key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
 
-      - run: pnpm install
-        working-directory: DefinitelyTyped
-      - run: pnpm ls
-        working-directory: DefinitelyTyped
+      - run: |
+          # If we're deleting packages, pnpm won't know what other unrelated packages
+          # need to be reinstalled that may now be sourced from npm instead of the
+          # local repo. Just pay the cost of the full install.
+          if git diff --diff-filter=DR --name-only master | grep -q 'package.json'; then
+            pnpm install
+          else
+            pnpm install --filter . --filter '...[origin/master]'
+          fi
 
-      - uses: actions/checkout@v3
-        with:
-          repository: microsoft/DefinitelyTyped-tools
-          path: DefinitelyTyped-tools
-          ref: pnpm-workspaces
-
-      - run: pnpm install
-        working-directory: DefinitelyTyped-tools
-
-      # REMOVEME: fixing missing depo
-      # - run: |
-      #     cd packages/header-parser
-      #     pnpm add semver
-      #     pnpm add -D @types/semver
-      #   working-directory: DefinitelyTyped-tools
-
-      - run: pnpm run build
-        working-directory: DefinitelyTyped-tools
-
-      - run: for i in ../DefinitelyTyped-tools/packages/*; do pnpm link $i; done
-        working-directory: DefinitelyTyped
+      - run: npm ls --all || true
 
       # Run tests
-      - run: NODE_ENV=test pnpm run test-all --selection all --shardId ${{ matrix.index }} --shardCount ${{ matrix.numJobs }}
-        working-directory: DefinitelyTyped
+      - run: pnpm run test-all
 
-  # compile_all:
-  #   runs-on: ubuntu-latest
+      - name: 'Run Danger'
+        env:
+          # See https://github.com/danger/danger-js/issues/1042
+          DANGER_GITHUB_API_BASE_URL: 'https://api.github.com'
 
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
-  #       numJobs: [20]
-
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version: '16'
-
-  #     # forbid symlinks
-  #     - name: 'Pre-run validation'
-  #       run: |
-  #         symlinks="$(find . -type l)"
-  #         if [[ -n "$symlinks" ]]; then
-  #           printf "Aborting: symlinks found:\n%s" "$symlinks"; exit 1
-  #         fi
-
-  #     - uses: pnpm/action-setup@v2
-  #       name: Install pnpm
-  #       id: pnpm-install
-  #       with:
-  #         version: latest
-  #         run_install: false
-
-  #     - name: Get pnpm cache info
-  #       id: pnpm-cache
-  #       shell: bash
-  #       run: |
-  #         echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT
-  #         echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT
-
-  #     - uses: actions/cache@v3
-  #       name: Setup pnpm cache
-  #       with:
-  #         path: ${{ steps.pnpm-cache.outputs.store }}
-  #         key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
-
-  #     - run: pnpm install
-  #     - run: pnpm ls
-
-  #     - run: |
-  #         shopt -s globstar
-  #         for i in types/**/tsconfig.json; do echo $i; done | grep -v node_modules | sort > all.txt
-  #         split -n l/${{ matrix.index }}/${{ matrix.numJobs }} all.txt \
-  #           | xargs -n1 node ./scripts/compile-one.js
+        # Danger failing (for example through rate-limiting) shouldn't fail the build
+        run: |
+          # Exposing this token is safe because the user of it has no other public repositories
+          # and has no permission to modify this repository. See #62638 for the discussion.
+          TOKEN='ghp_i5wtj1l2AbpFv3OU96w6R'
+          TOKEN+='On3bHOkcV2AmVY6'
+          DANGER_GITHUB_API_TOKEN=$TOKEN pnpm danger ci || $( exit 0 )
